name: 🔄 Mettre à jour le badge de version

on:
  push:
    paths:
      - version.txt

jobs:
  update-version-badge:
    runs-on: ubuntu-latest
    name: Générer le badge dynamique

    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v3

      - name: 🔧 Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 🛠 Installer les dépendances (facultatif)
        run: pip install -U pip

      - name: 🚀 Lancer le script de génération du badge
        run: python generate_badge.py

      - name: 📤 Commit & Push des changements
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/version-badge.json
          git commit -m "🔄 MAJ automatique du badge de version" || echo "Pas de changement"
          git push
